package:
  name: nsidc0530
  version: "0.0.1"

source:
  path: .

requirements:
  build:
    - python 3.5.*
    - pyyaml
    - setuptools
  run:
    - netcdf4
    - numpy
    - python 3.5.*

build:
  script:
    - python setup.py install

about:
  home: https://github.com/CATEES/nsidc0530
